#!/bin/bash
FILES=./"$1"/*
dirEntered="$1"
len=${#dirEntered}
len=$(($len+3))
rm tokens.txt 2> /dev/null
for f in $FILES
do
  echo "Tokenizing ${f:len} file..."
  # take action on each file. $f store current file name
	./_build/scanner < $f
	echo -ne "${f:len}" >> tokens.txt
	echo -ne " " >> tokens.txt
	cat scanner_out.txt >> tokens.txt
	echo "" >> tokens.txt
done
echo "Detecting Plagarism, this may take a few minutes."
./_build/cmos > PlagarismReport.txt
echo "Done. Results stored in PlagarismReport.txt"
